name: Chlorine
main: io.github.devalphagot.cl.Main
version: 1.008
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.20
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20
  - org.jetbrains.kotlin:kotlin-reflect:2.1.20
  - io.github.R2turnTrue:chzzk4j:0.0.12

permissions:
  cl.general:
    description: 명령어 사용 권한
    default: true